cmake_minimum_required(VERSION 3.22)
project(libprobabilityx)
#set(CMAKE_CXX_STANDARD 26)
#set(CMAKE_CXX_STANDARD_REQUIRED True)
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
find_package(Boost 1.84.0 COMPONENTS)
add_compile_options(-Wall -Werror -pedantic-errors -std=c++26 -fconcepts-diagnostics-depth=2)
include_directories(probabilityx/)
if(Boost_FOUND)
  include_directories(${Boost_INCLUDE_DIRS})
  add_executable(CompilerTest Test.cpp)
  add_executable(RangeTest RangeTest.cpp)
  add_executable(RollTest RollTest.cpp)
  add_library(AWStats OBJECT AWStats.cpp)
  add_executable(AWTest $<TARGET_OBJECTS:AWStats> AWTest.cpp)
  add_executable(AWCalculator $<TARGET_OBJECTS:AWStats> AWCalculator.cpp)
  target_link_libraries(CompilerTest ${Boost_LIBRARIES})
  target_link_libraries(RangeTest ${Boost_LIBRARIES})
  target_link_libraries(RollTest ${Boost_LIBRARIES})
  target_link_libraries(AWTest ${Boost_LIBRARIES})
  target_link_libraries(AWCalculator ${Boost_LIBRARIES})
endif()